=== scitran/api/raml/schemas/output/config.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "site": {
      "type": "object",
      "properties": {
        "central_url": {
          "type": "string"
        },
        "ssl_cert": {
          "type": "null"
        },
        "api_url": {
          "type": "string"
        },
        "registered": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "central_url",
        "ssl_cert",
        "api_url",
        "registered",
        "id",
        "name"
      ]
    },
    "modified": {
      "type": "string"
    },
    "auth": {
      "type": "object",
      "properties": {
        "id_endpoint": {
          "type": "string"
        },
        "verify_endpoint": {
          "type": "string"
        },
        "client_id": {
          "type": "string"
        },
        "auth_endpoint": {
          "type": "string"
        }
      },
      "required": [
        "id_endpoint",
        "verify_endpoint",
        "client_id",
        "auth_endpoint"
      ]
    },
    "created": {
      "type": "string"
    }
  },
  "required": [
    "site",
    "modified",
    "auth",
    "created"
  ]
}

=== scitran/api/raml/examples/scitran_config.json
{
	"site": {
		"central_url": "https://sdmc.scitran.io/api",
		"ssl_cert": null,
		"api_url": "https://10.240.0.2:443/api",
		"registered": false,
		"id": "local",
		"name": "BaliDemo"
	},
	"modified": "2016-03-31T16:30:00.852000+00:00",
	"auth": {
		"id_endpoint": "https://www.googleapis.com/plus/v1/people/me/openIdConnect",
		"verify_endpoint": "https://www.googleapis.com/oauth2/v1/tokeninfo",
		"client_id": "949263322061-6q4fqi0m4ihkp1v5n6v8q9bef4gd0f1k.apps.googleusercontent.com",
		"auth_endpoint": "https://accounts.google.com/o/oauth2/auth"
	},
	"created": "2016-03-31T16:30:00.852000+00:00"
}
