=== scitran/api/raml/schemas/output/job-list.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type":"object",
    "properties":{
      "_id":{"$ref":"../definitions/job.json#/definitions/id"},
      "name":{"$ref":"../definitions/job.json#/definitions/name"},
      "inputs":{"$ref":"../definitions/job.json#/definitions/inputs-array"},
      "destination":{"$ref":"../definitions/job.json#/definitions/destination"},
      "tags":{"$ref":"../definitions/job.json#/definitions/tags"},
      "state":{"$ref":"../definitions/job.json#/definitions/state"},
      "attempt":{"$ref":"../definitions/job.json#/definitions/attempt"},
      "created":{"$ref":"../definitions/created-modified.json#/definitions/created"},
      "modified":{"$ref":"../definitions/created-modified.json#/definitions/modified"},
      "config":{"$ref":"../definitions/job.json#/definitions/config"}
    },
    "additionalProperties":false,
    "required":[
       "_id", "name", "inputs",
       "destination", "tags", "state", "attempt"
    ]
  }
}

=== scitran/api/raml/examples/output/job-list.json
[
    {
        "inputs": [
          {
            "input": "dicom",
            "type": "acquisition",
            "id": "57d75ec38e4eb9699b3c245e",
            "name": "1_1_dicom.zip"
          }
        ],
        "attempt": 1,
        "name": "dcm-convert",
        "tags": [
            "dcm-convert"
        ],
        "destination": {
            "type": "acquisition",
            "id": "57ac7394c700190017123fb7"
        },
        "modified": "2016-08-11T12:46:12.593000+00:00",
        "created": "2016-08-11T12:46:12.593000+00:00",
        "state": "pending",
        "_id": "57ac7394c700190017123fb8",
        "config":{
            "speed":3
        }
    },
    {
        "inputs": [
            {
                "input":"dicom",
                "type": "acquisition",
                "id": "57ac7394c700190017123fb7",
                "name": "8403_4_1_t1_dicom.zip"
            }
        ],
        "attempt": 1,
        "name": "dcm_convert",
        "tags": [
          "ad-hoc",
          "dcm_convert"
        ],
        "destination": {
          "type": "acquisition",
          "id": "573c9e6a844eac7fc01747cd"
        },
        "modified": "2016-08-11T13:02:09.055000+00:00",
        "created": "2016-08-11T13:02:09.055000+00:00",
        "state": "pending",
        "_id": "57ac77515e325c0018cd17cf",
        "config":{
            "speed":3
        }
    }
]
