=== scitran/api/raml/schemas/mongo/collection.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Collection",
    "type": "object",
    "allOf": [{"$ref": "container.json"}],
    "properties": {
        "_id": {},
        "created": {},
        "modified": {},
        "permissions": {},
        "files": {},
        "public": {},
        "label": {},
        "tags": {},
        "metadata": {},

        "curator": {"type": "string"}
    },
    "additionalProperties": false
}

=== scitran/api/raml/examples/output/groups-list.json
[
    {
      "label": "Test Group",
      "permissions": [
        {
          "access": "admin",
          "_id": "group_admin@fakeuser.com",
          "phi-access": true
        },
        {
          "access": "rw",
          "_id": "group_member_read-write@fakeuser.com",
          "phi-access": true
        },
        {
          "access": "ro",
          "_id": "group_member_read-only@fakeuser.com",
          "phi-access": true
        }
      ],
      "created": "2016-08-19T11:41:15.360000+00:00",
      "modified": "2016-08-19T11:41:15.360000+00:00",
      "_id": "test_group"
    }
]
